### ISSUE TITLE
Any way to check if the field is dirty?

### ISSUE THREAD

**Issue by jackysee** [xpepermint/vue-rawmodel#9]
For example, create a new form with two field, username and password, both are required. To prevent immediate showing of error, the vue watch has set `immediate:false`. But when the user start typing 
username,  the password field would render error. It would be useful if there  is something like `user.getField('username').isDirty()`.
```
    <div>
      <input type="text" v-model="username" />
      <span v-if="user.getField('username').hasErrors()">
        {{ user.getField('username').errors | firstMessage }}
      </span>
    </div>
    <div>
      <input type="text" v-model="password" />
      <span v-if="user.getField('password').hasErrors()">
        {{ user.getField('password').errors | firstMessage }}
      </span>
    </div>
```

**Comment by xpepermint** [comment]
There is only the [isChanged](https://github.com/xpepermint/rawmodeljs/blob/master/src/fields.ts#L309) method for now.

**Comment by jackysee** [comment]
I guess that would be enough for my case, just make sure do not initialize when creating new model.
